import Link from 'next/link'
import { MessageCircle, Mail, CheckCircle, Wrench, AlertTriangle, MapPin, ChevronRight, ShieldCheck } from 'lucide-react'
import WhatsappCTA from '../../../components/WhatsappCTA'
import LangSwitcher from '../../../components/LangSwitcher'

export const metadata = {
  title: 'Alat Ganti Traktor John Deere Malaysia — Siri 5E, 5310 & 6J | SourceSage',
  description: 'Alat ganti traktor John Deere Malaysia. Seal hidraulik, komponen elektrik, alat ganti enjin. Rangkaian perolehan pelbagai pembekal untuk alat ganti yang tidak distok oleh pengedar tempatan.',
  alternates: { canonical: '/ms/john-deere-parts-malaysia/', languages: { 'en': 'https://sourcesage.ai/john-deere-parts-malaysia/', 'ms': 'https://sourcesage.ai/ms/john-deere-parts-malaysia/', 'zh-Hans': 'https://sourcesage.ai/zh/john-deere-parts-malaysia/', 'x-default': 'https://sourcesage.ai/john-deere-parts-malaysia/' } },
  openGraph: {
    title: 'Alat Ganti Traktor John Deere Malaysia — Siri 5E, 5310 & 6J | SourceSage',
    description: 'Alat ganti traktor John Deere Malaysia. Seal hidraulik, komponen elektrik, alat ganti enjin. Rangkaian perolehan pelbagai pembekal.',
    url: 'https://sourcesage.ai/ms/john-deere-parts-malaysia/',
    siteName: 'SourceSage.ai', type: 'website', locale: 'ms_MY',
    images: [{ url: 'https://sourcesage.ai/images/og-home.png', width: 1200, height: 630, alt: 'Alat Ganti Traktor John Deere Malaysia — SourceSage' }],
  },
  twitter: { card: 'summary_large_image', title: 'Alat Ganti Traktor John Deere Malaysia — Siri 5E, 5310 & 6J | SourceSage', description: 'Alat ganti traktor John Deere Malaysia. Seal hidraulik, komponen elektrik, alat ganti enjin.', images: ['https://sourcesage.ai/images/og-home.png'] },
}

const MODELS = [
  { model: 'John Deere 5075E', engine: 'JD PowerTech 3.4L 4-sil', note: 'JD moden paling popular di sektor sawah Malaysia' },
  { model: 'John Deere 5310', engine: 'JD 3029D / 3029T 3.0L', note: 'Meluas digunakan di estet padi Kedah, Kelantan' },
  { model: 'John Deere 5055E', engine: 'JD PowerTech 3.4L 4-sil', note: 'Utiliti peringkat permulaan, biasa di ladang kecil' },
  { model: 'John Deere 6110J / 6115J', engine: 'JD PowerTech 6.8L 6-sil', note: 'Kuda kerja ladang & estet besar' },
  { model: 'John Deere 5403 / 5415', engine: 'JD 3029D', note: 'Model legasi dengan pangkalan terpasang besar' },
  { model: 'JD 2WD Klasik (4020, 4040)', engine: 'Pelbagai enjin JD', note: 'Unit vintaj masih beroperasi di estet lama' },
]

const PARTS = [
  { category: 'Enjin (PowerTech / 3029)', items: ['Kit overhaul / bina semula penuh', 'Kepala silinder & set gasket kepala', 'Muncung penyuntik (Stanadyne / Bosch)', 'Pam air & termostat', 'Set gear masa & aci sesondol'] },
  { category: 'Transmisi & PTO', items: ['Cakera klac & plat tekanan', 'Seal aci PTO & galas', 'Gelang segerak & garpu anjakan', 'Seal & galas pacuan akhir', 'Komponen kunci pembeza'] },
  { category: 'Hidraulik (Litar Terbuka)', items: ['Pam hidraulik', 'Seal silinder angkat & omboh', 'Kit O-ring injap kawalan', 'Penapis hidraulik & penuras', 'Seal gandingan jauh'] },
  { category: 'Stereng & Gandar Hadapan', items: ['Kit bina semula silinder stereng', 'Set raja pin & bush', 'Galas hub roda hadapan', 'Hujung rod stereng & bebola', 'Seal kotak gear stereng'] },
  { category: 'Elektrik & Instrumen', items: ['Motor penghidup (12V)', 'Alternator & pengatur', 'Palam pijar (jenis 6-volt)', 'Penghantar suhu & tekanan minyak', 'Kluster instrumen & tolok'] },
  { category: 'Penapis & Barang Servis', items: ['Penapis minyak enjin (spesifikasi JD)', 'Penapis bahan api primer & sekunder', 'Elemen penapis udara & pra-pembersih', 'Penapis hidraulik / transmisi', 'Hos radiator & tali sawat'] },
]

const FAQS = [
  { q: 'Adakah anda menyimpan alat ganti John Deere tulen atau aftermarket?', a: 'Kami mendapatkan kedua-duanya — alat ganti John Deere tulen melalui saluran sah untuk komponen pemacu utama, dan aftermarket serasi OEM (contohnya Stanadyne, Bosch) untuk barang guna habis dan haus. Kami membincangkan pilihan dan harga untuk setiap permintaan alat ganti.' },
  { q: 'Pengedar John Deere saya kata alat ganti ini telah dihentikan. Bolehkah anda bantu?', a: 'Ya. Untuk model lama seperti 5310 dan 5403, kami mendapatkan dari pasaran sekunder Jepun dan pakar pembongkar. Alat ganti yang dihentikan secara rasmi di Malaysia selalunya boleh ditemui melalui saluran ini.' },
  { q: 'Model John Deere apa yang anda sokong?', a: 'Terutamanya siri 5E dan 6J yang biasa di Malaysia, ditambah model lama 5310, 5403, dan 5415. Untuk unit vintaj (4020, 4040), kami menilai ketersediaan kes demi kes.' },
  { q: 'Berapa cepat anda boleh hantar?', a: 'Untuk barang dalam stok, biasanya 1–3 hari bekerja di Semenanjung Malaysia, 3–5 hari untuk Malaysia Timur. Barang diperoleh dari Jepun atau China mengambil 10–21 hari. Kami sahkan masa utama sebelum anda komited.' },
  { q: 'Bolehkah saya hantar gambar alat ganti yang rosak daripada nombor alat ganti?', a: 'Semestinya. Gambar yang jelas — depan, belakang, dengan pembaris atau syiling untuk skala — biasanya membolehkan kami mengenal pasti komponen dan memadankannya dengan nombor alat ganti dalam beberapa jam.' },
]

export default function MsJohnDeerePage() {
  const serviceSchema = { '@context': 'https://schema.org', '@type': 'Service', 'inLanguage': 'ms', name: 'Perolehan Alat Ganti Traktor John Deere Malaysia', serviceType: 'Bekalan Alat Ganti Pertanian', description: 'Perolehan alat ganti traktor John Deere sukar dicari di seluruh Malaysia — siri 5E, 6J, 5310 dan model vintaj.', provider: { '@type': 'Organization', name: 'SourceSage.ai', url: 'https://sourcesage.ai' }, areaServed: { '@type': 'Country', name: 'Malaysia' } }
  const breadcrumbSchema = { '@context': 'https://schema.org', '@type': 'BreadcrumbList', 'inLanguage': 'ms', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Laman Utama', item: 'https://sourcesage.ai/ms/' }, { '@type': 'ListItem', position: 2, name: 'Alat Ganti John Deere Malaysia', item: 'https://sourcesage.ai/ms/john-deere-parts-malaysia' }] }
  const faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', 'inLanguage': 'ms', mainEntity: FAQS.map(f => ({ '@type': 'Question', name: f.q, acceptedAnswer: { '@type': 'Answer', text: f.a } })) }
  const partsListSchema = { '@context': 'https://schema.org', '@type': 'ItemList', 'inLanguage': 'ms', name: 'Kategori Alat Ganti John Deere', description: 'Alat ganti traktor John Deere mengikut sistem — enjin, transmisi, hidraulik, stereng & gandar, elektrik, penapis & servis.', numberOfItems: PARTS.length, itemListElement: PARTS.map((cat, i) => ({ '@type': 'ListItem', position: i + 1, item: { '@type': 'Product', name: `John Deere ${cat.category}`, description: `${cat.items.join(', ')}` } })) }
  const speakableSchema = { '@context': 'https://schema.org', '@type': 'SpeakableSpecification', 'inLanguage': 'ms', xpath: ["/html/head/title", "/html/head/meta[@name='description']/@content"] }

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(serviceSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(partsListSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(speakableSchema) }} />
      <WhatsappCTA label="ms-jd-sticky" message="Hi, saya perlukan alat ganti traktor John Deere. Model: ___ Alat ganti diperlukan: ___" className="fixed bottom-6 right-6 z-50 bg-green-500 hover:bg-green-600 text-white px-5 py-3.5 rounded-full shadow-2xl font-bold text-sm flex items-center gap-2 transition-all hover:scale-105"><MessageCircle className="w-5 h-5" /> WhatsApp Kami</WhatsappCTA>
      <div className="min-h-screen font-sans text-slate-900 antialiased">
        <nav className="bg-white shadow-sm sticky top-0 z-50">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex justify-between items-center">
            <Link href="/ms" className="flex items-center"><span className="font-heading font-bold text-xl text-accent tracking-tight">SourceSage</span><span className="font-bold text-xl text-green-600">.ai</span></Link>
            <div className="hidden md:flex gap-8 text-sm font-semibold text-slate-600">
              <Link href="/ms/#brands" className="hover:text-accent transition-colors">Jenama</Link>
              <Link href="/ms/#marine" className="hover:text-accent transition-colors">Marin</Link>
              <Link href="/ms/#how-it-works" className="hover:text-accent transition-colors">Cara Kerja</Link>
              <Link href="/ms/about" className="hover:text-accent transition-colors">Tentang</Link>
              <Link href="/ms/blog" className="hover:text-accent transition-colors">Blog</Link>
              <Link href="/ms/#request" className="hover:text-accent transition-colors">Minta Sebut Harga</Link>
            </div>
            <div className="flex items-center gap-2">
              <LangSwitcher currentLang="ms" />
              <WhatsappCTA label="ms-jd-navbar" message="Hi, saya perlukan alat ganti traktor John Deere. Model: ___ Alat ganti diperlukan: ___" className="bg-green-500 hover:bg-green-600 text-white px-4 py-2.5 rounded-lg font-bold transition-all text-sm flex items-center gap-2"><MessageCircle className="w-4 h-4" /> WhatsApp Kami</WhatsappCTA>
            </div>
          </div>
        </nav>
        <div className="bg-slate-50 border-b border-slate-100"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-3 text-sm text-slate-500"><Link href="/ms" className="hover:text-accent transition-colors">Laman Utama</Link><span className="mx-2">/</span><span className="text-slate-700 font-medium">Alat Ganti John Deere Malaysia</span></div></div>
        <section className="bg-gradient-to-br from-green-900 via-green-800 to-green-700 text-white py-20"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><div className="inline-block bg-yellow-400 text-green-900 text-xs font-black uppercase tracking-widest px-3 py-1.5 rounded-full mb-6">Pakar Alat Ganti John Deere — Malaysia</div><h1 className="text-4xl sm:text-5xl font-extrabold leading-tight mb-6">Alat Ganti Traktor John Deere<br />di Malaysia</h1><p className="text-lg text-green-100 mb-8 leading-relaxed">Perolehan alat ganti John Deere sukar dicari di seluruh Semenanjung dan Malaysia Timur — siri 5E dan 6J, model lama 5310 dan 5403, dan unit vintaj. Tulen dan serasi OEM. Respons pantas, harga kompetitif.</p><div className="flex flex-col sm:flex-row gap-4"><WhatsappCTA label="ms-jd-hero-primary" message="Hi, saya perlukan alat ganti traktor John Deere. Model: ___ Alat ganti diperlukan: ___" className="bg-yellow-400 hover:bg-yellow-300 text-green-900 px-8 py-4 rounded-xl font-black text-lg transition-all flex items-center gap-3 justify-center"><MessageCircle className="w-6 h-6" /> Minta Alat Ganti</WhatsappCTA><a href="#models" className="border-2 border-green-300 text-green-100 hover:bg-green-700 px-8 py-4 rounded-xl font-bold text-lg transition-all text-center">Lihat Model Disokong</a></div></div></div></section>
        <section className="bg-white border-b border-slate-100 py-6"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="grid grid-cols-2 md:grid-cols-4 gap-6 text-center">{[{label: 'Masa respons', value: '< 24 jam'},{label: 'Model dilindungi', value: '5E, 6J, 5310, 5403+'},{label: 'Liputan', value: 'Semenanjung + Timur MY'},{label: 'Sumber', value: 'Tulen & Serasi OEM'}].map(({ label, value }) => (<div key={label}><div className="text-xl font-black text-green-700">{value}</div><div className="text-xs text-slate-500 font-semibold mt-1">{label}</div></div>))}</div></div></section>
        <section id="models" className="py-16 bg-slate-50"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="mb-2 text-xs font-bold uppercase tracking-widest text-green-700">Model Disokong</div><h2 className="text-3xl font-extrabold text-slate-900 mb-4">Model John Deere Yang Kami Sumber Alat Ganti</h2><p className="text-slate-500 mb-10 max-w-2xl">Siri 5E dan 5310 menguasai sawah padi Malaysia; 6J biasa di estet yang lebih besar. Kami juga menyokong model lama di mana bekalan alat ganti pengedar telah menipis.</p><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">{MODELS.map(({ model, engine, note }) => (<div key={model} className="bg-white rounded-2xl border border-slate-100 p-6 shadow-sm"><div className="font-black text-lg text-slate-900 mb-1">{model}</div><div className="text-xs font-bold text-green-700 uppercase tracking-wide mb-2">{engine}</div><p className="text-slate-500 text-sm">{note}</p></div>))}</div><p className="mt-6 text-sm text-slate-400 italic">Tidak nampak model anda? Hubungi kami — kami menilai ketersediaan untuk semua peralatan pertanian John Deere.</p></div></section>
        <section className="py-16 bg-white"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="mb-2 text-xs font-bold uppercase tracking-widest text-green-700">Katalog Alat Ganti</div><h2 className="text-3xl font-extrabold text-slate-900 mb-4">Apa Yang Kami Sumber</h2><p className="text-slate-500 mb-10 max-w-2xl">Dari kit overhaul untuk enjin PowerTech dan 3029 hingga seal hidraulik dan komponen elektrik — kami meliputi spektrum penyelenggaraan dan pembaikan penuh.</p><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">{PARTS.map(({ category, items }) => (<div key={category} className="bg-slate-50 rounded-2xl p-6 border border-slate-100"><div className="flex items-center gap-2 mb-4"><Wrench className="w-4 h-4 text-green-700" /><h3 className="font-bold text-slate-900">{category}</h3></div><ul className="space-y-2">{items.map(item => (<li key={item} className="flex items-start gap-2 text-sm text-slate-600"><CheckCircle className="w-4 h-4 text-green-500 flex-shrink-0 mt-0.5" />{item}</li>))}</ul></div>))}</div></div></section>
        <section className="py-12 bg-yellow-50 border-y border-yellow-100"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><div className="flex items-start gap-4"><AlertTriangle className="w-6 h-6 text-yellow-600 flex-shrink-0 mt-1" /><div><h3 className="font-bold text-slate-900 text-lg mb-2">Kenali Kod Enjin JD Anda Sebelum Memesan</h3><p className="text-slate-600 text-sm leading-relaxed mb-4">John Deere menggunakan beberapa keluarga enjin merentasi julat traktornya: <strong>3029D/T</strong> (3.0L 3-silinder) dalam model 5310 dan 5403 lama, dan <strong>PowerTech 3.4L</strong> (3029DF/TF) dalam 5055E dan 5075E. Ini berkongsi beberapa komponen tetapi penyuntik, kit overhaul, dan kepala silinder adalah khusus model. Menyebut nombor siri enjin — dijumpai pada blok berhampiran alternator — memastikan anda mendapat alat ganti yang betul.</p><p className="text-slate-600 text-sm leading-relaxed">Siri 6J menggunakan enjin <strong>6.8L PowerTech 6-silinder</strong> (6068). Alat ganti untuk enjin ini berbeza sama sekali dan tidak boleh dipesan silang dengan unit 4-silinder.</p></div></div></div></div></section>
        <section className="py-16 bg-green-900 text-white"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="mb-2 text-xs font-bold uppercase tracking-widest text-green-300">Sabah &amp; Sarawak</div><h2 className="text-3xl font-extrabold mb-4">Kami Liput Malaysia Timur Juga</h2><p className="text-green-100 mb-8 max-w-2xl">Peralatan John Deere biasa di estet kelapa sawit dan padi Sabah dan Sarawak. Kami hantar ke Kota Kinabalu, Sandakan, Tawau, Kuching, Miri, dan Sibu — rangkaian perolehan sama, masa respons sama.</p><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3 mb-8">{['Kota Kinabalu', 'Sandakan', 'Tawau', 'Kuching', 'Miri', 'Sibu'].map(city => (<div key={city} className="flex items-center gap-2 bg-green-800 rounded-xl px-3 py-2.5"><MapPin className="w-3 h-3 text-green-300 flex-shrink-0" /><span className="text-sm font-semibold text-green-100">{city}</span></div>))}</div><WhatsappCTA label="ms-jd-east-malaysia" message="Hi, saya perlukan alat ganti traktor John Deere — saya di Malaysia Timur (Sabah/Sarawak). Model: ___ Alat ganti diperlukan: ___" className="inline-flex items-center gap-3 bg-yellow-400 hover:bg-yellow-300 text-green-900 px-8 py-4 rounded-xl font-black text-base transition-all"><MessageCircle className="w-5 h-5" /> WhatsApp untuk Pertanyaan Malaysia Timur</WhatsappCTA></div></section>
        <section className="py-16 bg-white"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="mb-2 text-xs font-bold uppercase tracking-widest text-green-700">Kenapa Kami</div><h2 className="text-3xl font-extrabold text-slate-900 mb-10">Kenapa Pengendali Malaysia Pilih SourceSage</h2><div className="grid md:grid-cols-3 gap-8">{[{icon: <ShieldCheck className="w-6 h-6 text-green-600" />, title: 'Di Luar Rangkaian Pengedar', body: 'Apabila pengedar sah kata "tidak lagi dikeluarkan" atau memberi masa utama 6 minggu, kami pergi ke pasaran sekunder Jepun, kilang serasi OEM di Taiwan, dan pakar pembongkar tempatan untuk mencari apa yang anda perlukan.'},{icon: <Wrench className="w-6 h-6 text-green-600" />, title: 'Kepakaran Kod Enjin', body: 'Kami tahu perbezaan antara 3029D dan 3029TF, dan kenapa ia penting untuk pesanan penyuntik anda. Pengenalan yang betul mengelakkan penghantaran balik yang mahal dan masa henti.'},{icon: <MessageCircle className="w-6 h-6 text-green-600" />, title: 'Respons WhatsApp Pantas', body: 'Hantarkan nombor alat ganti, gambar, atau hanya terangkan kerosakan. Kami membalas dengan ketersediaan dan harga — biasanya dalam 24 jam, seringkali hari yang sama.'}].map(({ icon, title, body }) => (<div key={title} className="flex gap-4"><div className="flex-shrink-0 w-12 h-12 bg-green-50 rounded-xl flex items-center justify-center">{icon}</div><div><h3 className="font-bold text-slate-900 mb-2">{title}</h3><p className="text-slate-500 text-sm leading-relaxed">{body}</p></div></div>))}</div></div></section>
        <section className="py-16 bg-slate-50"><div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8"><div className="mb-2 text-xs font-bold uppercase tracking-widest text-green-700">Soalan Lazim</div><h2 className="text-3xl font-extrabold text-slate-900 mb-10">Soalan Lazim</h2><div className="space-y-6">{FAQS.map(({ q, a }) => (<div key={q} className="bg-white rounded-2xl border border-slate-100 p-6 shadow-sm"><h3 className="font-bold text-slate-900 mb-3">{q}</h3><p className="text-slate-600 text-sm leading-relaxed">{a}</p></div>))}</div></div></section>
        <section className="py-20 bg-gradient-to-br from-green-900 to-green-800 text-white"><div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 text-center"><h2 className="text-3xl sm:text-4xl font-extrabold mb-4">Perlukan Alat Ganti John Deere?</h2><p className="text-green-100 text-lg mb-8">Beritahu kami model dan apa yang anda perlukan. Kami akan kembali dengan ketersediaan dan harga — biasanya dalam 24 jam.</p><WhatsappCTA label="ms-jd-final-cta" message="Hi, saya perlukan alat ganti traktor John Deere. Model: ___ Siri: ___ Alat ganti diperlukan: ___" className="inline-flex items-center gap-3 bg-yellow-400 hover:bg-yellow-300 text-green-900 px-10 py-5 rounded-2xl font-black text-xl transition-all"><MessageCircle className="w-7 h-7" /> WhatsApp Kami Sekarang</WhatsappCTA><p className="text-green-300 text-sm mt-6">Atau emel: info@sourcesage.ai</p></div></section>
        <footer className="bg-white py-12 text-slate-500 border-t border-slate-100"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="flex flex-col md:flex-row justify-between items-center gap-6 mb-8"><div><span className="font-heading font-black text-xl tracking-tighter text-accent">SourceSage</span><span className="font-black text-xl text-green-600">.ai</span><p className="text-sm text-slate-500 mt-1">Ipoh, Perak — Pakar Perolehan Alat Ganti di Malaysia</p></div><div className="flex gap-6 text-sm font-semibold"><a href="mailto:info@sourcesage.ai" className="hover:text-accent flex items-center gap-2 transition-colors"><Mail className="w-4 h-4" /> info@sourcesage.ai</a><WhatsappCTA label="ms-jd-footer" message="Hi, saya perlukan alat ganti traktor John Deere. Model: ___ Alat ganti diperlukan: ___" className="hover:text-green-600 flex items-center gap-2 transition-colors"><MessageCircle className="w-4 h-4" /> WhatsApp</WhatsappCTA></div></div><div className="text-center pt-6 border-t border-slate-100"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-slate-400">© 2026 SourceSage.ai. Perolehan Alat Ganti Pertanian &amp; Marin, Malaysia.</p></div></div></footer>
      </div>
    </>
  )
}
